#!/usr/bin/env bash

SRC=src
REMOTE=s11
DOMAIN=dupunkto.org

# Skip `tools` directory on remote
DEPLOY="$DEPLOY --exclude tools --exclude press"

deploy() {
  $DEPLOY $SRC/ $REMOTE:domains/$DOMAIN/public_html
}

serve() {
  cd $SRC
  waiter --dev
}