#!/bin/bash -eu

SRC=src
DIST=dist

REMOTE=s11
DOMAIN=dupunkto.org

build() {
  rsync -au --delete $SRC/ $DIST/
}

deploy() {
  if [ -d $DIST ]; then
    rsync -ciavuP --delete $DIST/ $REMOTE:domains/$DOMAIN/public_html
  else
    echo >&2 "Error: '$DIST' does not exist."
    echo >&2
  fi
}
